apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
    - name: kafka-external
      port: 30092
      targetPort: 30092
      nodePort: 30092   # fixed NodePort
  selector:
    app: kafka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
            - containerPort: 30092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"

            # Listeners - bind to all interfaces
            - name: KAFKA_LISTENERS
              value: EXTERNAL://0.0.0.0:30092,PLAINTEXT_INTERNAL://0.0.0.0:9092

            # What clients see
            - name: KAFKA_ADVERTISED_LISTENERS
              value: EXTERNAL://localhost:30092,PLAINTEXT_INTERNAL://kafka-service.default.svc.cluster.local:9092

            # Mapping for all listeners
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: EXTERNAL:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT

            # Inter-broker communication uses internal
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT_INTERNAL

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: anirudhsk17/consumer:1
          imagePullPolicy: IfNotPresent
          name: consumer
          env:
          - name: BOOTSTRAP_SERVERS
            value: kafka-service:9092

